### ISSUE TITLE
Add new multiplechoice question to Volunteer Signup Page

### ISSUE THREAD

**Issue by nelitos** [kiva/CrowdVet#1]
In the page where potential volunteers apply, we should add the below question: 

**What would you like to get out of Kiva Corps crowd-vetting platform (select all hat apply)?**
1. to use my knowledge and skills to help social enterprises get financing 
2. to learn about impact investing
3. to learn about social enterprise
4. to learn about due diligence of early stage companies
5. to support Kiva
6. Other: [please enter input]

**Comment by abhishekbh** [comment]
@nelitos, this is on the Volunteer signup form?

**Comment by nelitos** [comment]
Yes, the page where volunteers fill out their e-mail.

**Comment by rachelc421** [comment]
After speaking with @danielanastos , we decided to hold off from adding this question along with the three other questions in this issue (https://github.com/kiva/CrowdVet/issues/3) to the MVP rollout. Since we're only launching this to a small group of people, it's not necessary that we rush to add these questions to the flow, which would compromise the simplicity of the sign-up page. 

I suggest we create a new page with these three questions, which will show up after the user signs up successfully. We'll store the values in the db and then navigate the user to the Volunteer Home page. Daniel mentioned there was a need to surface these questions on the Admin page, which would also increase the scope of these tickets.  

If we still want to volunteers to answer these questions, I suggest we just send them a google form or surveymonkey at first. We can write a script or something and input those values into the backend when we revisit this. 

cc: @abhishekbh @avgj0e - should we close this out as a Won't Fix and open a new ticket to capture this new work?

**Comment by abhishekbh** [comment]
Agreed. Closing as Won't Fix. @avgj0e has fixed #3 in his own branch.
